Fix new-update-version with theme

diff --git a/.github/workflows/new-update-version.yml b/.github/workflows/new-update-version.yml
--- a/.github/workflows/new-update-version.yml
+++ b/.github/workflows/new-update-version.yml
@@ -83,6 +83,7 @@ jobs:
           echo "slug: ${{ inputs.slug }}"
           echo "version: ${{ inputs.version }}"
           echo "url: ${{ inputs.url }}"
+          echo "type: ${{ inputs.type }}"
 
       # Twofold: First we need to get the token into the future steps
       # and additionally we need to clone this repo into the baseRepo folder.
@@ -112,21 +113,21 @@ jobs:
           -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/orgs/${{ github.repository_owner }}/repos \
-          -d '{"name":"${{ inputs.slug }}","description":"This Repository Tracks the ${{inputs.slug}} private wordpress plugin.","private":true,"has_issues":false,"has_projects":false,"has_wiki":false, "gitignore_template":"WordPress"}'
+          -d '{"name":"${{ inputs.slug }}","description":"This Repository Tracks the ${{inputs.slug}} private wordpress ${{inputs.type}}.","private":true,"has_issues":false,"has_projects":false,"has_wiki":false, "gitignore_template":"WordPress"}'
 
-      - name: Clone Plugin Repo
+      - name: Clone ${{inputs.type}} Repo
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.ORG_ADMIN_TOKEN }} # `ORG_ADMIN_TOKEN` is a secret that contains your PAT
-          path: plugin
+          path: ${{ inputs.type }}
           repository: ${{ github.repository_owner }}/${{ inputs.slug }}
 
-      - name: Initialize Plugin Repo
+      - name: Initialize ${{inputs.type}} Repo
         if: ${{steps.check-remote.outputs.EXISTS == 'false'}}
         run: |
-          cd plugin
+          cd ${{inputs.type}}
           vendor=${{ inputs.vendor }}
-          echo -e "{\n\"name\": \"${{inputs.vendor == '' && inputs.slug || inputs.vendor}}/${{inputs.slug}}\",\n\"description\": \"Private Repo tracking the paid plugin ${{inputs.slug}}\"\n\"type\": \"wordpress-plugin\"\n}" >> composer.json
+          echo -e "{\n\"name\": \"${{inputs.vendor == '' && inputs.slug || inputs.vendor}}/${{inputs.slug}}\",\n\"description\": \"Private Repo tracking the paid ${{inputs.theme}} ${{inputs.slug}}\"\n\"type\": \"wordpress-${{inputs.type}}\"\n}" >> composer.json
           echo "---- Directory Structure ----"
           ls -la
           git config user.name "github-actions[bot]"
@@ -137,45 +138,45 @@ jobs:
           echo " " >> .gitignore
           git status
           git add *
-          git commit -m "Prepare Plugin Repo"
+          git commit -m "Prepare ${{inputs.type}} Repo"
           git push
 
       # the way this works is that we will move the .git folder to a new folder, then delete everything in the plugin folder, then fetch the new plugin files, then move the .git folder back into the plugin folder. This is because we need to keep the git history of the plugin files.
       - name: Remove Git from Local Files
         run: |
           mkdir GitInfo
-          cd plugin
+          cd ${{inputs.type}}
           git init --separate-git-dir=../GitInfo/git
           cp .git ../GitInfo/gitBackup
           echo "---- New Git Folder ----"
           cat ../GitInfo/gitBackup
 
-      - name: Remove Everything in Plugin Folder
+      - name: Remove Everything in ${{inputs.type}} Folder
         run: |
           echo "---- Directory Structure ----"
           ls -la
-          rm -rf plugin
+          rm -rf ${{inputs.type}}
           echo "---- Directory Structure ----"
           ls -la
-          mkdir plugin
+          mkdir ${{inputs.type}}
           echo "---- Directory Structure ----"
           ls -la
-          cd plugin
-          echo "---- Directory Structure plugin ----"
+          cd ${{inputs.type}}
+          echo "---- Directory Structure ${{inputs.type}} ----"
           ls -la
 
-      - name: Fetch Plugin Files
+      - name: Fetch ${{inputs.type}} Files
         run: |
-          curl -L "${{ inputs.url }}" > plugin.zip
-          unzip plugin.zip -d plugin
-          rm plugin.zip
+          curl -L "${{ inputs.url }}" > ${{inputs.type}}.zip
+          unzip ${{inputs.type}}.zip -d ${{inputs.type}}
+          rm ${{inputs.type}}.zip
 
       # Check the directory structure of the plugin to make sure that the slug provided was correct.
 
-      - name: Check that the plugin slug is correct
+      - name: Check that the ${{inputs.type}} slug is correct
         run: |
-          echo "---- Directory Structure of plugin ----"
-          cd plugin/${{ inputs.slug }} 
+          echo "---- Directory Structure of ${{inputs.type}} ----"
+          cd ${{inputs.type}}/${{ inputs.slug }} 
           ls -la
 
       # Now that we have the files locally lets make sure that the provided version & Slug matches the version in the plugin files
@@ -190,28 +191,41 @@ jobs:
           [[ $PLUGIN_VERSION == "${{ inputs.version }}" ]] && \
           { echo "Versions Match"; } || \
           { echo "Version Match Failed" && exit 1; }
+        when: inputs.type == 'plugin'
 
-      - name: Add git back to the plugin folder
+      - name: Check that the Theme Version Matches provided Version
         run: |
-          cd plugin/${{ inputs.slug }}
+          cd theme/${{ inputs.slug }}
+          THEME_VERSION=$(grep -Poh "(^|\s|^\*)+(Version\s*:\s*)\K([0-9]|\.)*(?=\s|$)" style.css)
+          echo "Theme Version: $THEME_VERSION"
+          echo "Input Version: ${{ inputs.version }}"
+          echo "---"
+          [[ $THEME_VERSION == "${{ inputs.version }}" ]] && \
+          { echo "Versions Match"; } || \
+          { echo "Version Match Failed" && exit 1; }
+        when: inputs.type == 'theme'
+
+      - name: Add git back to the ${{inputs.type}} folder
+        run: |
+          cd ${{inputs.type}}/${{ inputs.slug }}
           mv ../../GitInfo/git .git
 
       - name: check git status
         run: |
-          cd plugin/${{ inputs.slug }}
+          cd ${{inputs.type}}/${{ inputs.slug }}
           git status
 
       # if a plugin author provides a composer json file use theirs, otherwise use the default we created when we initialized the repo.
       - name: Check if composer.json exists
         id: check-composer
         run: |
-          cd plugin/${{ inputs.slug }}
+          cd ${{inputs.type}}/${{ inputs.slug }}
           [ -f composer.json ] && echo "Composer File Exists" && echo "EXISTS=true">>$GITHUB_OUTPUT || echo "Composer File Does Not Exist" && echo "EXISTS=false">>$GITHUB_OUTPUT
 
       - name: Add Composer File if not exist
         if: ${{steps.check-composer.outputs.EXISTS == 'false'}}
         run: |
-          cd plugin/${{ inputs.slug }}
+          cd ${{inputs.type}}/${{ inputs.slug }}
           echo "--- Directory Structure ---"
           ls -la
           git checkout -- composer.json
@@ -220,18 +234,18 @@ jobs:
 
       - name: Git Status 2
         run: |
-          cd plugin/${{ inputs.slug }}
+          cd ${{inputs.type}}/${{ inputs.slug }}
           git status
 
       # Finally push the new plugin files to the repo
-      - name: Push Plugin Files
+      - name: Push ${{inputs.type}} Files
         run: |
-          cd plugin/${{ inputs.slug }}
+          cd ${{inputs.type}}/${{ inputs.slug }}
           git add -A
           git status
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          git commit -m "Update Plugin to ${{ inputs.version }}"
+          git commit -m "Update ${{inputs.type}} to ${{ inputs.version }}"
           git push
           git tag ${{ inputs.version }}
           git push origin ${{ inputs.version }}
@@ -239,9 +253,9 @@ jobs:
       - name: Get Commit Hash
         id: get-commit-hash
         run: |
-          cd plugin/${{ inputs.slug }}
+          cd ${{inputs.type}}/${{ inputs.slug }}
           REFERENCE=$(git rev-parse --short HEAD)
-          echo "Git Hash for plugin: $REFERENCE"
+          echo "Git Hash for ${{inputs.type}}: $REFERENCE"
           echo "REFERENCE=$REFERENCE" >> $GITHUB_OUTPUT
 
       # use node to the version of the plugin in the database.json file.
@@ -253,12 +267,12 @@ jobs:
           cd baseRepo
           git pull
 
-      - name: Update the plugin version in the database
+      - name: Update the ${{inputs.type}} version in the database
         id: valid-update
         run: |
           cd baseRepo
           bun install
-          bun run ./src/update-plugin-version.ts --slug ${{ inputs.slug }} --update_version ${{ inputs.version }} --reference ${{ steps.get-commit-hash.outputs.REFERENCE }} --vendor ${{ inputs.vendor }}
+          bun run ./src/update-package-version.ts --slug ${{ inputs.slug }} --update_version ${{ inputs.version }} --reference ${{ steps.get-commit-hash.outputs.REFERENCE }} --vendor ${{ inputs.vendor }} --type ${{ inputs.type }}
 
       - name: Push updated Database to the Repo
         run: |
